spring:
  application:
    name: activity-service

  mongodb:
    uri: mongodb://docker:docker@localhost:27017/fitness_activity_db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082