spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://docker:docker@localhost:27018/fitness_ai_db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
