services:
  mongo:
    image: mongo:7
    container_name: aiservice-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
      MONGO_INITDB_DATABASE: fitness_ai_db
