services:
  postgres:
    image: postgres:17
    container_name: userservice-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitness_user_db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
